apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-ruby
  namespace: database
spec:
  selector:
    matchLabels:
      app: db-statefulset
  serviceName: db-service
  replicas: 3
  template:
    metadata:
      labels:
        app: db-statefulset
    spec:
      containers:
      - name: db-statefulset
        image: postgres:14.2-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_USER
                name: db-config

          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: db-config

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: ruby-secret-db
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
          - name: data-volume
            mountPath: "/var/lib/postgresql/data"
      volumes:
        - name:  data-volume
          persistentVolumeClaim:
            claimName: db-pvc
