apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-deployment
  namespace: ruby
spec:
  selector:
    matchLabels:
      app: ruby-deployment
  template:
    metadata:
      labels:
        app: ruby-deployment
    spec:
      containers:
      - name: ruby-budgy
        image: tharun13055/budgy:latest
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_USER
                name: ruby-db-config
          - name: POSTGRES_NAME
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_NAME
                name: ruby-db-config
          - name: Budgy_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: Budgy_DATABASE_PASSWORD
                name: ruby-secret
        command: [ "sh", "-c", "bin/rails db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'" ]
        resources:
          limits:
            memory: "1024Mi"
            cpu: "100m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
